### ISSUE TITLE
Request / approve identities prefixed with `SOURCE_`

### ISSUE THREAD

**Issue by bbockelm** [HTPhenotyping/registration#13]
Instead of whitelisting identities one-by-one, we've taken to whitelisting `STARTD_*` at the collector.

Since we're calling these data sources now, let's modernize that to `SOURCE_*` -- but we still want the prefix.  That'll require a quick update to `register.py`

If we don't do this, we'll need to reconfig `htpheno-cm` every time we add a new source.

**Comment by JoshKarpel** [comment]
Clarify - the idea is that every source name should be prefixed with `SOURCE_`, and you want this enforced in the registration script? Does the user have to enter that manually, or do we prefix it ourselves and tell them we did it later?

**Comment by bbockelm** [comment]
> the idea is that every source name should be prefixed with SOURCE_, and you want this enforced in the registration script?

Correct

> Does the user have to enter that manually, or do we prefix it ourselves and tell them we did it later?

We will add the prefix ourselves - unless users start debugging things, we will aim to make this invisible / never tell them about it.  The source name is still `Morgridge_Bockelman` even if HTCondor uses the identity `SOURCE_Morgridge_Bockelman@users.htcondor.org`.
