### ISSUE TITLE
Add registration script 

### ISSUE THREAD

**Issue by JoshKarpel** [HTPhenotyping/registration#2]
Pull rough draft from https://github.com/htcondor/htcondor-ce/pull/299

**Comment by bbockelm** [comment]
The existing node install script here:

https://github.com/HTPhenotyping/execute_node_config/blob/master/deploy_htcondor.sh

The documentation page is likely going to recommend some variant of running the following as `root`:

```
curl https://github.com/HTPhenotyping/execute_node_config/blob/master/deploy_htcondor.sh | bash
```

So, once we have the registration script available, it likely needs to be appended to the above file...
