### ISSUE TITLE
Add `READ` permission to tokens

### ISSUE THREAD

**Issue by bbockelm** [HTPhenotyping/registration#21]
After I install a data source, how do I test everything is working?!?

Do we:
1.  Allow `READ` to everyone?
2. Add `READ` permissions to generated tokens?

**Comment by JoshKarpel** [comment]
Restricting `READ` to people that have the token is obviously safer, but would that mean that regular users on the data source machine wouldn't be able to check that they're connected? What does the check constitute? `condor_status` and seeing themselves? Maybe we could pack that up as a little bash (`am_i_connected`) and install it as part of the regular install process.

**Comment by JoshKarpel** [comment]
This was resolved by https://github.com/HTPhenotyping/registration/commit/1ac149ea20977e5e4d6473ff205099a8e60368a7
