### ISSUE TITLE
Add signup form

### ISSUE THREAD

**Issue by JoshKarpel** [HTPhenotyping/registration#3]
The entrypoint of the registration flow should be a signup form that ends up sending an email to the administrator email list (or maybe even opening a GitHub issue?). The user will enter various biographical information like their name and contact email, as well as the data source they want to register. We check the data source name for uniqueness, capture their OID eppn, and send off the email for processing by a human.

**Comment by bbockelm** [comment]
Done - initial submit form is in place.
