### ISSUE TITLE
Installation page should provide customized commands

### ISSUE THREAD

**Issue by JoshKarpel** [HTPhenotyping/registration#35]
If the user is on the installation page, we already know everything we need to know about them (except maybe their data source directory?) to tell them exactly what to run for the installation. Now that we have #34 , we can inject the right command into the HTML when we serve up the page.

**Comment by jasoncpatton** [comment]
At least for the default project, we don't need the data source directory. Perhaps we should remove it from the registration page until we start handling multiple projects?
